services:
    postgres:
        image: postgres:17.4
        ports: 
           - 5432:5432
        environment:
           POSTGRES_DB: library
           POSTGRES_USER: admin
           POSTGRES_PASSWORD: sahil