services:
  db:
    image: postgres
    restart: always
    environment:
                POSTGRES_PASSWORD: sahil
                POSTGRES_USER: admin
                POSTGRES_DB: sessions
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
    db_data:           